# See full doc at https://artifacthub.io/packages/helm/bitnami/mongodb
fullnameOverride: hohomalls-mongo
architecture: standalone

image:
  debug: true

auth:
  existingSecret: hohomalls

service:
  type: NodePort
  nodePort: 30000
