# See full doc at https://artifacthub.io/packages/helm/bitnami/redis
fullnameOverride: hohomalls-redis
architecture: standalone

image:
  debug: true

auth:
  existingSecret: hohomalls
  existingSecretPasswordKey: redis-password

master:
  service:
    type: NodePort
    nodePort: 30100
