# See full doc at https://artifacthub.io/packages/helm/bitnami/redis
fullnameOverride: hohomalls-redis
architecture: standalone

image:
  debug: true

auth:
  existingSecret: hohomalls
  existingSecretPasswordKey: redis-password

volumePermissions:
  enabled: true

master:
  nodeSelector:
    nodeType: hohomalls-data-worker
  service:
    type: NodePort
    nodePort: 30100
