---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hohomalls-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hohomalls-app
  template:
    metadata:
      labels:
        app: hohomalls-app
    spec:
      containers:
        - name: hohomalls-app
          image: hohomalls-app:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "1024m"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: hohomalls
                  key: active-profile
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: hohomalls
                  key: redis-host
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hohomalls
                  key: redis-password
            - name: SPRING_DATA_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: hohomalls
                  key: mongodb-host
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hohomalls
                  key: mongodb-root-user
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hohomalls
                  key: mongodb-root-password
            - name: COM_HOHOMALLS_TOKEN_PUBLIC-KEY
              valueFrom:
                secretKeyRef:
                  name: hohomalls
                  key: token-public-key
            - name: COM_HOHOMALLS_TOKEN_PRIVATE-KEY
              valueFrom:
                secretKeyRef:
                  name: hohomalls
                  key: token-private-key
---
apiVersion: v1
kind: Service
metadata:
  name: hohomalls-app
spec:
  type: NodePort
  selector:
    app: hohomalls-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30200
