spring:
  redis:
    host: // FIXME
    username: // FIXME
    password: // FIXME
    ssl: true
  data:
    mongodb:
      host: // FIXME
      username: // FIXME
      password: // FIXME

com:
  hohomalls:
    token:
      public-key: // FIXME
      private-key: // FIXME
      lifespan: 240

dgs:
  graphql:
    graphiql:
      enabled: false