# See docs at https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
server:
  port: 8080

spring:
  redis:
    host: // FIXME
    username: // FIXME
    password: // FIXME
    ssl: true
  data:
    mongodb:
      host: // FIXME
      username: // FIXME
      password: // FIXME

# See docs at https://netflix.github.io/dgs/configuration/
dgs:
  graphql:
    graphiql:
      enabled: false

com:
  hohomalls:
    token:
      public-key: // FIXME
      private-key: // FIXME
      lifespan: 240