# See docs at https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
spring:
  redis:
    password: # Injected via environment variables
  data:
    mongodb:
      username: # Injected via environment variables
      password: # Injected via environment variables

# See docs at https://netflix.github.io/dgs/configuration/
dgs:
  graphql:
    graphiql:
      enabled: false

cloud:
  aws:
    region:
      static: # Injected via environment variables

com:
  hohomalls:
    web:
      multipart:
        base-storage-url: # Injected via environment variables
      token:
        public-key: # Injected via environment variables
        private-key: # Injected via environment variables