# See docs at https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
server:
  max-http-header-size: 64KB

spring:
  redis:
    port: 6379
  data:
    mongodb:
      port: 27017
      database: hohomalls
      auto-index-creation: true
      authentication-database: admin