spring:
  redis:
    port: 6379
  data:
    mongodb:
      port: 27017
      database: hohomalls
      auto-index-creation: true
      authentication-database: admin

com:
  hohomalls:
    token:
      lifespan: 240