spring:
  application:
    name: hohomalls-mongo
  data:
    mongodb:
      port: 27017
      database: hohomalls
      authentication-database: admin

mongock:
  migration-scan-package:
    - com.hohomalls.mongo.changeunit
  runner-type: applicationrunner
  throw-exception-if-cannot-obtain-lock: true
