spring:
  data:
    mongodb:
      host: # Injected via environment variables
      username: # Injected via environment variables
      password: # Injected via environment variables

mongock:
  transaction-enabled: true