mongock:
  change-unit-scan-package:
    - com.hohomalls.mongo.changeunit
  transaction-enabled: true
  runner-type: applicationrunner
  default-migration-author: hohomalls
  throw-exception-if-cannot-obtain-lock: true
