fullnameOverride: hohomalls-mongo
architecture: standalone

image:
  debug: true

global:
  namespaceOverride: hohomalls-local

persistence:
  size: 8Gi

auth:
  existingSecret: hohomalls

service:
  nameOverride: hohomalls-mongo
  type: NodePort
  nodePort: 30000
