kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hohomalls-prod
  name: hohomalls-hostpath
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G