apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.namespaceOverride }}
  name: {{ .Values.global.productName }}
data:
  spring-active-profile: {{ .Values.hohomalls.springActiveProfile }}
  redis-host: {{ .Values.redis.fullnameOverride }}-master
  mongodb-host: {{ .Values.mongodb.fullnameOverride }}