apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.productName }}
data:
  active-profile: {{ .Values.hohomalls.activeProfile }}
  redis-host: {{ .Values.redis.fullnameOverride }}-master
  redis-port: {{ .Values.hohomalls.redisPort | quote }}
  mongodb-host: {{ .Values.mongodb.fullnameOverride }}
  mongodb-port: {{ .Values.hohomalls.mongodbPort | quote }}
  base-storage-url: {{ .Values.hohomalls.baseStorageUrl | quote }}
