apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hohomalls.imageName }}
spec:
  replicas: {{ .Values.hohomalls.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.hohomalls.imageName }}
  template:
    metadata:
      labels:
        app: {{ .Values.hohomalls.imageName }}
    spec:
      nodeSelector:
        nodeType: hohomalls-app-worker
      containers:
        - name: hohomalls-app
          image: {{ .Values.hohomalls.imageName }}:{{ .Values.hohomalls.imageTag }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: {{ .Values.hohomalls.resources.limits.memory }}
              cpu: {{ .Values.hohomalls.resources.limits.cpu }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.productName }}
                  key: active-profile
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.productName }}
                  key: redis-host
            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.productName }}
                  key: redis-port
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.productName }}
                  key: redis-password
            - name: SPRING_DATA_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.productName }}
                  key: mongodb-host
            - name: SPRING_DATA_MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.productName }}
                  key: mongodb-port
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.productName }}
                  key: mongodb-root-user
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.productName }}
                  key: mongodb-root-password
            - name: COM_HOHOMALLS_WEB_MULTIPART_BASE-STORAGE-URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.productName }}
                  key: base-storage-url
            - name: COM_HOHOMALLS_WEB_TOKEN_PUBLIC-KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.productName }}
                  key: token-public-key
            - name: COM_HOHOMALLS_WEB_TOKEN_PRIVATE-KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.productName }}
                  key: token-private-key