apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.global.namespaceOverride }}
  name: {{ .Values.global.productName }}
type: Opaque
data:
  {{ .Values.redis.auth.existingSecretPasswordKey }}: {{ .Values.global.redisPassword }}
  mongodb-root-user: {{ .Values.global.mongodbRootUser }}
  mongodb-root-password: {{ .Values.global.mongodbRootPassword }}
  token-public-key: {{ .Values.hohomalls.tokenPublicKey }}
  token-private-key: {{ .Values.hohomalls.tokenPrivateKey }}
