apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespaceOverride }}
  name: {{ .Values.hohomalls.imageName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.hohomalls.imageName }}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.hohomalls.nodePort }}