version: "3.9"

networks:
  hohomalls-frontend:
  hohomalls-backend:

volumes:
  hohomalls-mongo-volume:
  hohomalls-redis-volume:
  hohomalls-app-volume:

services:
  # See doc at https://hub.docker.com/r/bitnami/mongodb
  mongo:
    container_name: hohomalls-mongo
    image: bitnami/mongodb:${VERSION_BITNAMI_MONGODB}
    environment:
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - hohomalls-mongo-volume:/bitnami/mongodb
    networks:
      - hohomalls-backend

  # See doc at https://hub.docker.com/r/bitnami/redis
  redis:
    container_name: hohomalls-redis
    image: bitnami/redis:${VERSION_BITNAMI_REDIS}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - hohomalls-redis-volume:/bitnami/redis/data
    networks:
      - hohomalls-backend

  hohomalls:
    container_name: hohomalls-app
    image: hohomalls-app:${VERSION_BITNAMI_HOHOMALLS_APP}
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_DATA_MONGODB_HOST: ${MONGODB_HOST}
      SPRING_DATA_MONGODB_USERNAME: ${MONGODB_ROOT_USER}
      SPRING_DATA_MONGODB_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      COM_HOHOMALLS_TOKEN_PUBLIC-KEY: ${TOKEN_PUBLIC_KEY}
      COM_HOHOMALLS_TOKEN_PRIVATE-KEY: ${TOKEN_PRIVATE_KEY}
    ports:
      - "8080:8080"
    volumes:
      - hohomalls-app-volume:/data
    depends_on:
      - mongo
      - redis
    networks:
      - hohomalls-backend
